gungnir/core/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required

from gungnir.core.views import ProfileView, DashboardView, DashboardListView

urlpatterns = patterns('gungnir.core.views',
    url(r'^$', RedirectView.as_view(url=reverse_lazy('gungnir-core-about')), name='gungnir-core-index'),
    url(r'^about/$', TemplateView.as_view(template_name='core/about.html'), name='gungnir-core-about'),
    url(r'^profile/$', login_required(ProfileView.as_view()), name='profile'),
    url(r'^dashboard/$', login_required(DashboardListView.as_view()), name='gungnir-core-dashboard'),

)

gungnir/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from core.forms import CompatEmailUserCreationForm, CoreEmailAuthForm
#from emailusernames.forms import EmailAuthenticationForm

from builds.views import *

from projects.views import *

urlpatterns = patterns('',
    url(r'^', include('gungnir.core.urls')),
    url(r'^projects/', include('gungnir.projects.urls')),

    url(r'^admin/', include(admin.site.urls)),

    # celery task views
    url(r'^builds/tasks/build_image/(?P<build_config_id>\d+)$', build_image_view),



    # generic views
    (r'^AwsBaseAmi/$',AwsBaseAmiView.as_view()),
    (r'^BuildConfig/$',BuildConfigView.as_view()),
    (r'^Build/$',BuildView.as_view()),
    (r'^SupervisordCommand/$',SupervisordCommandView.as_view()),
    (r'^PythonRequirements/$',PythonRequirementsView.as_view()),

    # django-celery
    url(r'^celery/', include('djcelery.urls')),
    
    # django-registration - this is retarded how they suggest you override these. fact, you should just not include these urls...
    url(r'^accounts/register/$',
        'registration.views.register',
        {
            'backend': 'registration.backends.default.DefaultBackend',
            'form_class': CompatEmailUserCreationForm,
            'extra_context':{'page_title':'Create Account', 'page_header':'Create Account', 'form_submit_text':'Create'}
        },
        name='registration_register'),
    url(r'^accounts/login/$',
        'django.contrib.auth.views.login',
        {'authentication_form': CoreEmailAuthForm,},
        name='auth_login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    # this has to be last, so stupid.
    (r'^accounts/', include('registration.backends.default.urls')),
)

gungnir/builds/models.py
from django.db import models
from gungnir.core.models import BaseModel
from gungnir.builds.builder import AwsGunicornUbuntu

from celery.execute import send_task
OS_CHOICES = (
    (0, 'ubuntu'),
    #(1, 'centos'),
    )



class AwsBaseAmi(BaseModel):
    AMI_REGION_CHOICES = (
        (0, 'us-east-1'),
        (1, 'us-west-1'),
    )
    AMI_ARCH_CHOICES = (
        (0, 'i386'),
        (1, 'amd64'),
    )
    AMI_STORAGE_CHOICES = (
        (0, 'ebs'),
        (1, 'instance-store'),
    )

    region = models.PositiveSmallIntegerField(choices=AMI_REGION_CHOICES, default=0)
    arch = models.PositiveSmallIntegerField(choices=AMI_ARCH_CHOICES, default=1)
    storage = models.PositiveSmallIntegerField(choices=AMI_STORAGE_CHOICES, default=0)
    ami_id = models.CharField(max_length=15)
    aki_id = models.CharField(max_length=15, blank=True)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.ami_id

class BuildConfig(BaseModel):
    WEBSERVER_CHOICES = (
    #   (0, 'apache'),
        (1, 'gunicorn'),
    )
    BUILD_TYPE_CHOICES = (
    #    (0, 'Deploy'),
        (1, 'AWS AMI'),
    )

    parent_config = models.ForeignKey('self', blank=True, null=True)
    application = models.ForeignKey('projects.Application', related_name='buildconfigs')
    repo = models.ForeignKey('projects.Repo', related_name='buildconfigs')

    os = models.PositiveSmallIntegerField(choices=OS_CHOICES, default=1)
    webserver = models.PositiveSmallIntegerField(choices=WEBSERVER_CHOICES, default=1)
    build_type = models.PositiveIntegerField(choices=BUILD_TYPE_CHOICES, default=1)

    # Virtual Env Stuff
    venv_requirements = models.CharField(max_length='256', default='requirements.txt')#models.ManyToManyField('PythonRequirements', blank=True, null=True)
    use_virtualenv = models.BooleanField(default=True) # dont use for now...
    deploy_root	 = models.CharField(max_length='256', default='/opt/venvs') # Location venvs will reside

    # django specific
    django_settings = models.CharField(max_length=256, default='settings') # Python path to settings file, will be used for configs

    static_root = models.CharField(max_length=256, blank=True) # Location of static root, None value will result in no files being served from the AMI
    media_root = models.CharField(max_length=256, blank=True) # Location of media root, None value will result in no files being served from the AMI

    # aws specific
    aws_base_ami = models.ForeignKey(AwsBaseAmi)
    aws_keypair_name = models.CharField(max_length=32) # no idea how long these can be
    aws_ami_public = models.BooleanField(default=True)  # Set this to make the AMIs produced public

    def __unicode__(self):
        return u'configuration-' + u'-'.join([self.application.name, self.repo.short_name])

    def get_builder(self):
        return AwsGunicornUbuntu(self)


class Build(BaseModel):
    """
    once we've built an ami from a config, put it here...
    """

    DEPLOY_STATES = (
        ('NOT STARTED', 'NOT STARTED'),
        ('IN PROGRESS', 'IN PROGRESS'),
        ('WAITING FOR INSTANCE', 'WAITING FOR INSTANCE'),
        ('CONFIGURING INSTANCE', 'CONFIGURING INSTANCE'),
        ('COMPLETED', 'COMPLETED'),
        ('FAILED', 'FAILED'),

    )

    application = models.ForeignKey('projects.Application', related_name='builds')
    config = models.ForeignKey(BuildConfig)
    ami_id = models.CharField(max_length=15)
    instance_id = models.CharField(max_length=15)
    code_version = models.CharField(max_length=10, blank=True)

    description = models.TextField()
    build_date = models.DateTimeField(auto_now_add=True)

    deploy_status = models.CharField(max_length=255, choices=DEPLOY_STATES, default='NOT STARTED')

    def save(self, *args, **kwargs):
        try:
            async_task = kwargs.pop('async_task')

        except KeyError:
            async_task = True

        results = super(Build, self).save(*args, **kwargs)

        if async_task:
            send_task('gungnir.builds.tasks.build_image', args=[self.config.pk])



        return results

#class Deploy()

class SupervisordCommand(BaseModel):
    build_config = models.ForeignKey(BuildConfig)
    name = models.CharField(max_length=255)
    cmd = models.CharField(max_length=255)  # Templated command name for example '/{deploy_root}/bin/manage.py' will fill in deploy_root from AMI
    directory = models.CharField(default='{PROJECT_ROOT}', max_length=255) # Directory to work out of
    user = models.CharField(default='root', max_length=64) # User to run the supd command as

class PythonRequirements(BaseModel):
    config = models.ManyToManyField('BuildConfig')
    os = models.PositiveSmallIntegerField(choices=OS_CHOICES, default=1)
    pypi_name = models.CharField(max_length=128) # Actual python package name that you would pass to pip
    os_package = models.CharField(max_length=128) # Required OS package for the package name
    build_only = models.BooleanField(default=False) # Indicate whether the package can be removed after AMI build

gungnir/core/models.py
from django.db import models
from django_extensions.db.fields import CreationDateTimeField, ModificationDateTimeField
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class BaseModel(models.Model):
    created = CreationDateTimeField()
    modified = ModificationDateTimeField()

    class Meta:
        abstract = True
        get_latest_by = 'modified'
        
class Profile(models.Model):
    class Meta:
        db_table = 'profile'
    user = models.OneToOneField(User)
    can_build = models.BooleanField(default=False, blank=True)
    aws_akey = models.CharField(max_length=64, blank=True,)
    aws_skey = models.CharField(max_length=64, blank=True,)
    ssh_key = models.FileField(upload_to='keys', blank=True, default='/tmp/djangodash2012.pem')
    
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.get_or_create(user=instance)
    post_save.connect(create_user_profile, sender=User)

gungnir/projects/models.py
from django.core.urlresolvers import reverse
from django.db import models
#from django_extensions.db.fields import SlugField
from gungnir.core.models import BaseModel


from git import Repo as GitRepo

from celery.execute import send_task
from gungnir.projects.utils import iter_find_files

import os

class Application(BaseModel):
    PROJECT_TYPE_CHOICES = (
        (0, 'Django'),
    )
    name = models.CharField(max_length=250)
    owner = models.ForeignKey('auth.User', related_name='applications')
    app_type = models.PositiveSmallIntegerField(choices=PROJECT_TYPE_CHOICES, default=0)

    def __unicode__(self):
        return u'{0}'.format(self.name)

    def get_absolute_url(self):
        return reverse('gungnir-projects-application-detail', kwargs={'pk':self.pk})

class Repo(BaseModel):
    application = models.ForeignKey(Application, related_name='repos')
    url = models.CharField(max_length=500)
    branch = models.CharField(max_length=50, default='master')
    path_on_disk = models.CharField(max_length=1024, blank=True, null=True)

    class Meta:
        unique_together = ('application', 'url', 'branch')

    def __unicode__(self):
        return self.branch + ' on ' + self.short_name


    @property
    def short_name(self):
        return self.url.split('/')[-1]

    def _branch_choices(self):
        if not self.repo_exists():
            return [('master', 'master')]
        else:
            branches = list()
            for branch in self.branches():
                branches.append((branch, branch))
        return branches


    def repo_exists(self):
        """Determine if path_on_disk is a valid repo or not"""
        try:
            if not os.path.exists(self.path_on_disk):
                return False

            GitRepo(self.path_on_disk)
            return True

        except Exception as e:
            return False

    def branches(self):
        repo = GitRepo(self.path_on_disk)

        branches = list()
        for branch in repo.branches:
            branches.append(branch.name)

        return branches

    def save(self, *args, **kwargs):
        try:
            async_task = kwargs.pop('async_task')
        except KeyError:
            async_task = True

        results = super(Repo, self).save(*args, **kwargs)

        if async_task:
            send_task('gungnir.projects.tasks.fetch_repo_for_existing_entry', args=(self.application.pk, self.url))

        return results

    def possible_requirement_files(self):
        requirements_glob = 'requirements.txt'
        iter_find_files(self.path_on_disk, 'requirements*' )


    def possible_settings_files(self):
        settings_glob = '*settings*py'
        iter_find_files(self.path_on_disk, 'settings')

gungnir/builds/forms.py
from django.forms import ModelForm
from gungnir.builds.models import *

class AwsBaseAmiForm(ModelForm):
    class Meta:
        model = AwsBaseAmi

class BuildConfigForm(ModelForm):
    class Meta:
        model = BuildConfig
        exclude = ('parent_config', 'application')

class BuildForm(ModelForm):
    class Meta:
        model = Build
        exclude = ('application', 'ami_id', 'instance_id', 'deploy_status', 'build_date')

class SupervisordCommandForm(ModelForm):
    class Meta:
        model = SupervisordCommand
        
class PythonRequirementsForm(ModelForm):
    class Meta:
        model = PythonRequirements

gungnir/core/forms.py
from emailusernames.forms import EmailUserCreationForm, EmailAuthenticationForm
from django.forms import ModelForm
from django import forms
from gungnir.core.models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user','can_build',)
    
    aws_akey = forms.CharField(label="Access Key")
    aws_skey = forms.CharField(label="Secret Key")
    
# workaround to get username-as-emails to work with django-registration
class CompatEmailUserCreationForm(EmailUserCreationForm):
    def clean(self):
        cleaned_data = super(CompatEmailUserCreationForm, self).clean()
        if cleaned_data.has_key('email'):
            cleaned_data['username'] = cleaned_data['email']
        return cleaned_data


from gungnir.core.decorators import order_fields
@order_fields('email','password')
class CoreEmailAuthForm(EmailAuthenticationForm):
    pass

gungnir/builds/views.py
from django.views.generic import TemplateView
from gungnir.builds.forms import *

from django.contrib.auth.decorators import login_required
from djcelery.views import task_view
from gungnir.builds.tasks import build_image

build_image_view = login_required(task_view(build_image))

class AwsBaseAmiView(TemplateView):
    template_name = "core/AwsBaseAmi.html"
    
    def get(self, request):
        return self.render_to_response({'form':AwsBaseAmiForm})
    
class BuildConfigView(TemplateView):
    template_name = "core/BuildConfig.html"
    
    def get(self, request):
        return self.render_to_response({'form':BuildConfigForm})
    
class BuildView(TemplateView):
    template_name = "core/Build.html"
    
    def get(self, request):
        return self.render_to_response({'form':BuildForm})
    
class SupervisordCommandView(TemplateView):
    template_name = "core/SupervisordCommand.html"
    
    def get(self, request):
        return self.render_to_response({'form':SupervisordCommandForm})
    
class PythonRequirementsView(TemplateView):
    template_name = "core/PythonRequirements.html"
    
    def get(self, request):
        return self.render_to_response({'form':PythonRequirementsForm})

gungnir/core/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView, ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from gungnir.core.forms import ProfileForm
from gungnir.projects.models import Application, Repo

def index(request):
    return render_to_response('core/base.html', {}, context_instance=RequestContext(request))


class ProfileView(TemplateView):
    template_name = "core/profile.html"
    
    @method_decorator(login_required)
    def get(self, request):
        profile = request.user.get_profile()
        
        form = ProfileForm({
            'aws_akey':profile.aws_akey,
            'aws_skey':profile.aws_skey,
        })
        return self.render_to_response({'form':form})
    
    @method_decorator(login_required)
    def post(self, request):
        form = ProfileForm(request.POST, request.FILES)
        profile = request.user.get_profile()
        
        if form.is_valid():
            profile.aws_akey=form.cleaned_data['aws_akey']
            profile.aws_skey=form.cleaned_data['aws_skey']
            profile.save()
        
        form = ProfileForm({
            'aws_akey':profile.aws_akey,
            'aws_skey':profile.aws_skey,
        })
        return self.render_to_response({'form':form})

class DashboardView(TemplateView):
    template_name =  "core/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['app_list'] = Application.objects.filter(owner=self.request.user)
        return context

class DashboardListView(ListView):
    model = Application
    template_name =  "core/dashboard.html"

    def get_queryset(self):
        qs = Application.objects.filter(owner=self.request.user)
        return qs

gungnir/core/templates/core/AwsBaseAmi.html
{% extends "core/base.html" %}

{% block content %}

{{ form }}

{% endblock %}

gungnir/core/templates/core/Build.html
{% extends "core/base.html" %}

{% block content %}

{{ form }}

{% endblock %}

gungnir/core/templates/core/BuildConfig.html
{% extends "core/base.html" %}

{% block content %}

{{ form }}

{% endblock %}

gungnir/core/templates/core/PythonRequirements.html
{% extends "core/base.html" %}

{% block content %}

{{ form }}

{% endblock %}

gungnir/core/templates/core/Repo.html
{% extends "core/base.html" %}

{% block content %}

{{ form }}

{% endblock %}

gungnir/core/templates/core/SupervisordCommand.html
{% extends "core/base.html" %}

{% block content %}

{{ form }}

{% endblock %}

gungnir/core/templates/core/about.html
{% extends "core/base.html" %}
{% block title %}Home{% endblock %}

{% block content %}

    <header class="jumbotron subhead" id="overview">
        <h1>Gungnir</h1>
        <p class="lead">Putting you in control of your deployments.</p>
    </header>
    <br>

    <section id="how">
        <div class="page-header">
            <h1>Manage, deploy, and scale your python apps in the cloud.</h1>
        </div>
        <div class="row">
            <div class="span4">
                <h3>Step 1: Add an Application</h3>
                <p>Gungnir makes it easy for you manage all of your apps through 1 account.</p>
                <p>Register today to get started!</p>
            </div>
            <div class="span4">
                <h3>Step 2: Create a Build Config</h3>
                <p>With the Gungnir build configuration system, you have total control over how your application instances get built.</p>
            </div>
            <div class="span4">
                <h3>Step 3: Deploy!!</h3>
                <p>Once you're happy with your build, you can roll them to your own AWS accounts and roll cloud-ready solutions in seconds!</p>
            </div>
        </div>
    </section>

    <br>
    <br>
    <section id="scale">
        <div class="page-header">
            <h1>EZmode Cloud Scaling</h1>
        </div>
        <div class="row">
            <div class="span6">
                <h3>AMI's</h3>
                <p>PUPPET! CHEF! SALT! FABRIC! HEROKU! learn to really scale with amazon without dealing with a middle man. Build an AMI like the big kids and stand up an ASG. We'll hold your hand through the hard parts.</p>
            </div>
        </div>
    </section>


{% endblock %}

gungnir/core/templates/core/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>{% block title %}Gungnir{% endblock %}</title>

    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.css">
{#    <link rel="stylesheet" href="{{ STATIC_URL }}css/font-awesome.css">#}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/gungnir.css">

    <script src="{{ STATIC_URL }}js/lib/jquery-1.8.0.min.js"></script>
    <script src="{{ STATIC_URL }}js/lib/underscore-min.js"></script>
    <script src="{{ STATIC_URL }}js/lib/backbone-min.js"></script>
    <script src="{{ STATIC_URL }}js/lib/handlebars-1.0.0.beta.6.js"></script>
    <script src="{{ STATIC_URL }}js/lib/bootstrap-alert.js"></script>
    
    {% block extrajs %}
    {% endblock %}

</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{% url gungnir-core-index %}">Gungnir</a>
                <ul class="nav pull-left">
                    {% block navbar-left %}
                        <li><a href="{% url gungnir-core-about %}">About</a></li>

                        {% if user.is_authenticated %}
                            <li><a href="{% url gungnir-core-dashboard %}">Dashboard</a></li>
                        {% endif %}

                    {% endblock %}
                </ul>
            {%  block navbar-right %}
                <ul class="nav pull-right">
                    {% if not user.is_authenticated %}
                        <li><a href="{% url auth_login %}">Login</a></li>
                        <li><a href="{% url registration_register %}">Register</a></li>
                    {% else %}
                        <li><p class="navbar-text">{{ user.username }}</p></li>
                        <li><a href="{% url profile %}">Profile</a></li>
                        <li><a href="{% url auth_logout %}">Logout</a></li>
                    {% endif %}
                </ul>
            {%  endblock %}
        </div>
    </div>

    <ul class="breadcrumb">
        {% block breadcrumbs %}
            <li>
                <a href="{% url gungnir-core-dashboard %}">Home</a>
            </li>
            
            <span class="divider">/</span>
            
            <!--
            <li>
                <a href="#">Library</a> 
            </li>
            
            <span class="divider">/</span>
            
            <li class="active" style="color: black">Data</li>
            -->
        {% endblock %}
    </ul>
</div>


<div class="container">


    <div class="content">

        {% block content %}

        {% endblock %}
    </div>

    <footer class="footer">
        <p class="pull-left">
            a badatcomputers production. trololol.
        </p>
        <p class="pull-right">
            <a href="#">Back to Top!</a>
        </p>
    </footer>
</div>



</body>
</html>

gungnir/core/templates/core/dashboard.html
{% extends "core/base.html" %}
{% block title %}Dashboard{% endblock %}

{% block navbar-left %}
    {{ block.super }}

{% endblock %}

{% block content %}
    <header class="jumbotron subhead" id="overview" xmlns="http://www.w3.org/1999/html">
        <h2>Application Dashboard</h2>
        <p>
            <a class="btn btn-inverse" href="{% url gungnir-projects-application-create %}">
            <i class="icon-plus icon-white"></i> Add Application</a>
        </p>
    </header>
    <br>
    
    {% if messages %}
        {% for message in messages %}
        <div class="alert">
          <button class="close" data-dismiss="alert">×</button>
          {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    
    {% for app in object_list %}
    <div class="page-header">
        <h2>{{ app.name }} ({{ app.get_app_type_display }})</h2>
    </div>


    <div class="row">
    <div class="span9">

        <div class="well">
            <h4>Repos</h4>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Repo URL</th>
                    <th>Watched Branch</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for  repo in app.repos.all %}
                <tr>
                    <td><a href="/projects/repo/{{ repo.id }}/">{{ repo.id }}</a></td>
                    <td>{{ repo.url }}</td>
                    <td>{{ repo.branch }}</td>
                    <td><a href="/projects/repo/update/{{ repo.id }}/"><button class="btn">Edit</button></a></td>
                    <td>
                        <form method="POST" action="/projects/repo/delete/{{ repo.id }}/">
                            {% csrf_token %}
                            <input type="submit" value="Delete" class="btn"/>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <p><a href="{% url gungnir-projects-repo-create app.pk %}"  class="btn btn-primary btn-small"><i class="icon-magnet icon-white"></i> Link Repo</a></p>
        </div>
    </div>
    </div>

    <div class="row">
    <div class="span9">
        <div class="well">
            <h4>BuildConfigs</h4>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Repo</th>
                    <th>OS</th>
                    <th>Web Server</th>
                    <th>Build Type</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for buildconfig in app.buildconfigs.all %}
                <tr>
                    <td><a href="/projects/buildconfig/{{ buildconfig.id }}/">{{ buildconfig.repo }}</a></td>
                    <td>{{ buildconfig.get_os_display }}</td>
                    <td>{{ buildconfig.get_webserver_display }}</td>
                    <td>{{ buildconfig.get_build_type_display }}</td>
                    <td><a href="/projects/buildconfig/update/{{ buildconfig.id }}/"><button class="btn">Edit</button></a></td>
                    <td>
                        <form method="POST" action="/projects/buildconfig/delete/{{ buildconfig.id }}/">
                            {% csrf_token %}
                            <input type="submit" value="Delete" class="btn"/>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <p><a href="{% url gungnir-projects-buildconfig-create app.pk %}"  class="btn btn-primary btn-small"><i class="icon-plus-sign icon-white"></i> Add Config</a></p>

        </div>

    </div>
    </div>


    <div class="row">
    <div class="span9">

        <div class="well">
            <h4>Builds</h4>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Build Config</th>
                    <th>Instance / AMI Id</th>
                    <th>Create Time</th>
                    <th>Build Status</th>
{#                    <th></th>#}
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for build in app.builds.all %}
                <tr>
                    <td><a href="/projects/build/{{ build.id }}/">{{ build.config }}</a></td>
                    <td>{{ build.ami_id }} {{ build.instance_id }}</td>
                    <td>{{ build.created|date:"D d M Y" }}</td>
                    <td>{{ build.deploy_status }}</td>
{#                    <td><a href="/projects/build/update/{{ build.id }}/"><button class="btn">Edit</button></a></td>#}
                    <td>
                        <form method="POST" action="/projects/build/delete/{{ build.id }}/">
                            {% csrf_token %}
                            <input type="submit" value="Delete" class="btn"/>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <p><a href="{% url gungnir-projects-build-create app.pk %}"  class="btn btn-info btn-small"><i class="icon-ok icon-white"></i> Build It!</a></p>
        </div>
    </div>
    </div>
    {% endfor %}

{% endblock %}



<table class="table table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>App Type</th>
    </tr>
    </thead>
</table>

gungnir/core/templates/core/form.html
{% extends "core/base.html" %}

{% load i18n %}

{% block title %}{{ page_title }}{% endblock %}

{% block extrajs %}
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ page_header }}</h1>
    </div>
    <div class="row">
    <div class="span8">
        <form method="POST" class="form-horizontal well" action="">
            <fieldset>
                {% csrf_token %}
                {% for field in form %}
                    <div class="control-group{% if field.errors %} error{% endif %}">
                        <label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
                        <div class="controls">
                            {{ field }} {% if field.errors %}<span class="help-inline">{{ field.errors }}</span>{% endif %}
                        </div>
                    </div>
                {% endfor %}

                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">{{ form_submit_text }}</button>
                </div>
            </fieldset>

        </form>
    </div>
    </div>
{% endblock content %}

gungnir/core/templates/core/profile.html
{% extends "core/base.html" %}

{% block content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>

<form method="POST" action=".">
{% csrf_token %}

{{ form }}
<br/>
<input type="submit" value="Save" class="btn">
</form>
{% endblock %}